CREATE TABLE test.ict_wln
( 
"MonthId" INT ENCODE ZSTD,
"MonthStartDt" DATE ENCODE ZSTD,
"CCYYMM" VARCHAR(15) ENCODE ZSTD,
"YearNum" VARCHAR(4) ENCODE ZSTD,
"LOB" VARCHAR(255) ENCODE ZSTD,
"LCDCustCd" VARCHAR(7) ENCODE ZSTD,
"Entity" VARCHAR(15) ENCODE ZSTD,
"BillgSystemCd" VARCHAR(15) ENCODE ZSTD,
"RCID" BIGINT ENCODE ZSTD,
"RCID_CUST_NM" VARCHAR(255) ENCODE ZSTD,
"CBU_CID" BIGINT ENCODE ZSTD,
"CBUCID_CUST_NM" VARCHAR(255) ENCODE ZSTD,
"TSMA_SPEND_IND" VARCHAR(31) ENCODE ZSTD,
"DataExclusion_flg" VARCHAR(15) ENCODE ZSTD,
"TSMA_SERVICE_TOWER" VARCHAR(255) ENCODE ZSTD,
"SAP_MIC_CD_flg" INT ENCODE ZSTD,
"SAP_MIC_CD" VARCHAR(63) ENCODE ZSTD,
"BPI_PROD_CD" VARCHAR(63) ENCODE ZSTD,
"BPI_PROD_DESC" VARCHAR(63) ENCODE ZSTD,
"PROD_FAMILY_CD" VARCHAR(15) ENCODE ZSTD,
"PROD_FAMILY_DESC" VARCHAR(63) ENCODE ZSTD,
"RN_1" VARCHAR(63) ENCODE ZSTD,
"RN_2" VARCHAR(63) ENCODE ZSTD,
"RN_3" VARCHAR(63) ENCODE ZSTD,
"RN_4" VARCHAR(63) ENCODE ZSTD,
"EPP3_DESC" VARCHAR(63) ENCODE ZSTD,
"EPP3_CD" VARCHAR(63) ENCODE ZSTD,
"Quantity" INT ENCODE ZSTD,
"BilledAmt" DECIMAL(10,2) ENCODE ZSTD,
"Comment"VARCHAR(255) ENCODE ZSTD
);

GRANT SELECT ON test.ict_wln TO "looker";
GRANT SELECT ON test.ict_wln TO "datamodeling";
