CREATE TABLE test.ict_wls
( 
"MonthId" INT ENCODE ZSTD,
"MonthStartDt" DATE ENCODE ZSTD,
"CCYYMM" VARCHAR(6) ENCODE ZSTD,
"YearNum" VARCHAR(4) ENCODE ZSTD,
"BillgSystemCd" VARCHAR(15) ENCODE ZSTD,
"BillgAcctCd" INT ENCODE ZSTD,
"BillgAcctNm" VARCHAR(255) ENCODE ZSTD,
"RCID" BIGINT ENCODE ZSTD,
"RCID_CUST_NM" VARCHAR(255) ENCODE ZSTD,
"CBU_CID" BIGINT ENCODE ZSTD,
"CBUCID_CUST_NM" VARCHAR(255) ENCODE ZSTD,
"LCDCustCd" VARCHAR(7) ENCODE ZSTD,
"LCDCategory" VARCHAR(255) ENCODE ZSTD,
"LOB" VARCHAR(255) ENCODE ZSTD,
"CreateDt" DATE ENCODE ZSTD,
"Total" VARCHAR(255) ENCODE ZSTD,
"ChargeType" VARCHAR(255) ENCODE ZSTD,
"ChargeSubType" VARCHAR(255) ENCODE ZSTD,
"LCD_flg" VARCHAR(255) ENCODE ZSTD,
"BilledAmt" DECIMAL(10,2) ENCODE ZSTD,
"ReasonDesc" VARCHAR(255) ENCODE ZSTD
);

GRANT SELECT ON test.ict_wls TO "looker";
GRANT SELECT ON test.ict_wls TO "datamodeling";
